seed: 42
device: cuda:0
train:
  epochs: 700
  batch_size: 256
  lr: 0.001
  weight_decay: 0.0001
  scheduler: cosine
  early_stopping_patience: 5
  gradient_clip_val: 1.0
  num_workers: 4
  stages_preset: two_stage
data:
  name: ptbxl_concept
  data_folder: ./datasets/ptbxl_concept
  n_var: 12
  seq_length: 1000
  normalize: false
model:
  name: timevqvae
  VQ-VAE:
    n_fft: 4
    codebook_sizes:
      lf: 1024
      hf: 1024
    codebook_dim: 8
  encoder:
    init_dim: 4
    hid_dim: 128
    n_resnet_blocks: 2
    downsampled_width:
      lf: 8
      hf: 32
  decoder:
    n_resnet_blocks: 2
  MaskGIT:
    choice_temperatures:
      lf: 10.0
      hf: 0.0
    T:
      lf: 10
      hf: 10
    cfg_scale: 1.0
  prior:
    hidden_dim: 128
    n_layers: 4
    heads: 2
    ff_mult: 1.0
    use_rmsnorm: true
    p_unconditional: 0.2
condition:
  text:
    enabled: false
    input_dim: 1024
  attribute:
    enabled: true
  label:
    enabled: true
    num_classes: 10
  fusion: concat
eval:
  metrics:
  - dtw
  - wape
  - ed
  - crps
  - acd
  - sd
  - kd
  - mdd
  - fid
  - jftsd
  - prdc_f1
  - joint_prdc_f1
  - cttp
  n_samples: 10
  batch_size: 128
  save_samples: true
  viz:
    enable: true
    n_cases: 20
    output_type: pdf
  clip_config_path: ./configs/cttp/<CTTP_CONFIG>.yaml
  clip_model_path: ./checkpoints/cttp/<CTTP_CHECKPOINT>.ckpt
  clip_normalize_embeddings: false
  cache_folder: ./cache/ptbxl_concept
  use_cache: true
