condition:
  attribute:
    enabled: true
  fusion: concat
  label:
    enabled: true
    num_classes: 10
  text:
    enabled: false
    input_dim: 1024
data:
  data_folder: ./datasets/telecomts_segment
  n_var: 2
  name: telecomts_segment
  normalize: false
  seq_length: 128
device: cuda:0
eval:
  batch_size: 128
  cache_folder: ./cache/telecomts_segment
  clip_config_path: ./configs/cttp/cttp_telecomts_instance.yaml
  clip_model_path: ./checkpoints/cttp/<CTTP_CHECKPOINT>.ckpt
  metrics:
  - dtw
  - wape
  - ed
  - crps
  - acd
  - sd
  - kd
  - mdd
  - fid
  - jftsd
  - prdc_f1
  - joint_prdc_f1
  - cttp
  n_samples: 10
  save_samples: true
  use_cache: true
  viz:
    enable: true
    n_cases: 20
    output_type: pdf
model:
  d_depth: 3
  g_depth: 3
  latent_dim: 100
  name: ttscgan
seed: 42
train:
  batch_size: 256
  early_stopping_patience: 50
  epochs: 700
  gradient_clip_val: 1.0
  lr: 0.001
  num_workers: 4
  scheduler: cosine
  weight_decay: 0.0001
