seed: 42
device: cuda:0
train:
  epochs: 700
  batch_size: 64
  lr: 0.001
  weight_decay: 0.0001
  scheduler: cosine
  early_stopping_patience: 50
  gradient_clip_val: 1.0
  num_workers: 4
data:
  name: ptbxl_concept
  data_folder: ./datasets/ptbxl_concept
  n_var: 12
  seq_length: 1000
  normalize: false
model:
  name: ttscgan
  latent_dim: 100
  data_embed_dim: 8
  d_embed_dim: 32
  g_num_heads: 4
  d_num_heads: 4
  d_patch_size: 50
  g_depth: 2
  d_depth: 2
condition:
  text:
    enabled: false
    input_dim: 1024
  attribute:
    enabled: true
  label:
    enabled: true
    num_classes: 10
  fusion: concat
eval:
  metrics:
  - dtw
  - wape
  - ed
  - crps
  - acd
  - sd
  - kd
  - mdd
  - fid
  - jftsd
  - prdc_f1
  - joint_prdc_f1
  - cttp
  n_samples: 10
  batch_size: 128
  save_samples: true
  viz:
    enable: true
    n_cases: 20
    output_type: pdf
  clip_config_path: ./configs/cttp/cttp_ptbxl_concept.yaml
  clip_model_path: ./checkpoints/cttp/<CTTP_CHECKPOINT>.ckpt
  clip_normalize_embeddings: false
  cache_folder: ./cache/ptbxl_concept
