#!/usr/bin/env python3
"""
Grid search for PTFactorGenerator V2 on ConTSG-Bench.

Generates YAML config files for each hyperparameter combination,
then produces a shell script to run all experiments sequentially.

Usage:
    python scripts/grid_search_ptfg.py --dataset synth-u
    python scripts/grid_search_ptfg.py --dataset synth-m
    python scripts/grid_search_ptfg.py --dataset synth-u --dataset synth-m

This will create:
    configs/grid_search/ptfg_<dataset>_<hash>.yaml   (one per combo)
    scripts/run_grid_<dataset>.sh                     (launcher script)
"""
import argparse
import hashlib
import itertools
import os
import yaml
from pathlib import Path
from copy import deepcopy


# ============================================================
# Grid search space
# ============================================================

GRID = {
    # Training hyperparameters (aligned with baseline range)
    "lr":          [5e-4, 7.5e-4, 1e-3],
    "batch_size":  [128, 256],

    # V2-specific: spectral loss weight
    "spectral_loss_weight": [0.0, 0.05, 0.1],

    # V2-specific: self-conditioning on/off
    "self_cond":   [True, False],

    # V2-specific: prediction type
    "prediction_type": ["v", "eps"],
}

# Fixed seed for grid search (single seed per combo to save compute;
# promising combos can later be run with 3 seeds)
GRID_SEED = 42

# ============================================================
# Dataset-specific base configs
# ============================================================

BASE_CONFIGS = {
    "synth-u": "configs/generators/ptfg_synth-u.yaml",
    "synth-m": "configs/generators/ptfg_synth-m.yaml",
}


def load_base_config(dataset: str) -> dict:
    path = BASE_CONFIGS[dataset]
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def make_combo_id(combo: dict) -> str:
    """Short deterministic hash for a parameter combination."""
    s = str(sorted(combo.items()))
    return hashlib.md5(s.encode()).hexdigest()[:8]


def apply_combo(base: dict, combo: dict) -> dict:
    """Apply a grid search combo to a base config dict."""
    cfg = deepcopy(base)

    # Training params
    cfg["train"]["lr"] = combo["lr"]
    cfg["train"]["batch_size"] = combo["batch_size"]
    for stage in cfg["train"].get("stages", []):
        stage["lr"] = combo["lr"]

    # Model params (V2-specific)
    cfg["model"]["spectral_loss_weight"] = combo["spectral_loss_weight"]
    cfg["model"]["self_cond"] = combo["self_cond"]
    cfg["model"]["prediction_type"] = combo["prediction_type"]

    # Seed
    cfg["seed"] = GRID_SEED

    return cfg


def combo_label(combo: dict) -> str:
    """Human-readable short label."""
    parts = []
    parts.append(f"lr{combo['lr']}")
    parts.append(f"bs{combo['batch_size']}")
    parts.append(f"spec{combo['spectral_loss_weight']}")
    parts.append(f"sc{'T' if combo['self_cond'] else 'F'}")
    parts.append(f"pred_{combo['prediction_type']}")
    return "_".join(parts)


def generate_configs(dataset: str, output_dir: Path) -> list:
    """Generate all grid search config files. Returns list of (config_path, label)."""
    base = load_base_config(dataset)
    output_dir.mkdir(parents=True, exist_ok=True)

    keys = sorted(GRID.keys())
    values = [GRID[k] for k in keys]
    combos = [dict(zip(keys, vals)) for vals in itertools.product(*values)]

    results = []
    for combo in combos:
        label = combo_label(combo)
        cid = make_combo_id(combo)
        filename = f"ptfg_{dataset}_{cid}.yaml"
        filepath = output_dir / filename

        cfg = apply_combo(base, combo)

        # Add a comment header (as a YAML field) for traceability
        cfg["_grid_search"] = {
            "combo_id": cid,
            "label": label,
            "params": combo,
        }

        with open(filepath, "w", encoding="utf-8") as f:
            yaml.dump(cfg, f, default_flow_style=False, allow_unicode=True, sort_keys=False)

        results.append((str(filepath), label, combo))

    return results


def generate_shell_script(dataset: str, configs: list, script_dir: Path):
    """Generate a shell script to run all grid search experiments."""
    script_dir.mkdir(parents=True, exist_ok=True)
    script_path = script_dir / f"run_grid_{dataset}.sh"

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        f"# Grid search for PTFG V2 on {dataset}",
        f"# Total combinations: {len(configs)}",
        f"# Generated by: python scripts/grid_search_ptfg.py --dataset {dataset}",
        "",
        'LOGDIR="log/grid_search"',
        "mkdir -p $LOGDIR",
        "",
    ]

    for i, (config_path, label, combo) in enumerate(configs, 1):
        log_file = f"$LOGDIR/ptfg_{dataset}_{label}.log"
        lines.append(f"# [{i}/{len(configs)}] {label}")
        lines.append(f'echo "[{i}/{len(configs)}] Running: {label}"')
        lines.append(
            f"contsg train --config {config_path} "
            f"2>&1 | tee {log_file}"
        )
        lines.append("")

    lines.append(f'echo "Grid search complete! {len(configs)} experiments finished."')
    lines.append(f'echo "Logs in: $LOGDIR"')

    with open(script_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Shell script: {script_path}")
    return script_path


def generate_summary_script(dataset: str, configs: list, script_dir: Path):
    """Generate a Python script to parse grid search results and rank combos."""
    script_path = script_dir / f"summarize_grid_{dataset}.py"

    code = '''#!/usr/bin/env python3
"""Parse grid search logs and rank hyperparameter combinations."""
import json
import re
import sys
from pathlib import Path

DATASET = "''' + dataset + '''"
LOG_DIR = Path("log/grid_search")
EXP_DIR = Path("experiments")

# Key metrics for ranking (lower is better for all except prdc)
RANK_METRICS = {
    "dtw": "lower",
    "crps": "lower",
    "acd": "lower",
    "fid": "lower",
    "jftsd": "lower",
    "prdc_f1.f1": "higher",
    "joint_prdc_f1.f1": "higher",
}


def parse_log(log_path: Path) -> dict:
    """Extract evaluation metrics from a log file."""
    metrics = {}
    text = log_path.read_text(encoding="utf-8", errors="ignore")

    # Parse table-style metrics
    for line in text.split("\\n"):
        line = line.strip()
        if "|" in line:
            # Match: │ metric_name  │  value │
            m = re.match(r".*?\\│\\s+(\\S+)\\s+\\│\\s+([\\d.]+)\\s+\\│", line)
            if m:
                name, val = m.group(1), m.group(2)
                try:
                    metrics[name] = float(val)
                except ValueError:
                    pass
    return metrics


def rank_combos():
    logs = sorted(LOG_DIR.glob(f"ptfg_{DATASET}_*.log"))
    if not logs:
        print(f"No logs found in {LOG_DIR} for dataset {DATASET}")
        sys.exit(1)

    results = []
    for log_path in logs:
        label = log_path.stem.replace(f"ptfg_{DATASET}_", "")
        metrics = parse_log(log_path)
        if metrics:
            results.append({"label": label, "metrics": metrics})

    if not results:
        print("No results parsed!")
        sys.exit(1)

    # Compute composite score: average rank across key metrics
    n = len(results)
    for metric_name, direction in RANK_METRICS.items():
        vals = [(i, r["metrics"].get(metric_name, float("inf") if direction == "lower" else 0.0))
                for i, r in enumerate(results)]
        vals.sort(key=lambda x: x[1], reverse=(direction == "higher"))
        for rank, (idx, _) in enumerate(vals):
            results[idx].setdefault("ranks", {})[metric_name] = rank + 1

    for r in results:
        r["avg_rank"] = sum(r.get("ranks", {}).values()) / max(len(r.get("ranks", {})), 1)

    # Sort by average rank
    results.sort(key=lambda r: r["avg_rank"])

    # Print results
    print(f"\\n{'='*80}")
    print(f"Grid Search Results: PTFG V2 on {DATASET}")
    print(f"{'='*80}")
    print(f"{'Rank':<5} {'Label':<55} {'AvgRank':<8} {'DTW':<10} {'CRPS':<10} {'ACD':<10} {'FID':<10}")
    print("-" * 80)
    for i, r in enumerate(results, 1):
        m = r["metrics"]
        print(f"{i:<5} {r['label']:<55} {r['avg_rank']:<8.1f} "
              f"{m.get('dtw', -1):<10.4f} {m.get('crps', -1):<10.4f} "
              f"{m.get('acd', -1):<10.4f} {m.get('fid', -1):<10.3f}")

    print(f"\\nBest combo: {results[0]['label']}")
    print(f"Full metrics: {json.dumps(results[0]['metrics'], indent=2)}")


if __name__ == "__main__":
    rank_combos()
'''
    with open(script_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(code)

    print(f"Summary script: {script_path}")


def main():
    parser = argparse.ArgumentParser(description="Grid search config generator for PTFG V2")
    parser.add_argument(
        "--dataset", "-d",
        action="append",
        choices=list(BASE_CONFIGS.keys()),
        required=True,
        help="Dataset(s) to generate grid search for",
    )
    args = parser.parse_args()

    config_dir = Path("configs/grid_search")
    script_dir = Path("scripts")

    total = 1
    for v in GRID.values():
        total *= len(v)
    print(f"Grid search space: {total} combinations per dataset")
    print(f"Parameters: {', '.join(f'{k}={v}' for k, v in GRID.items())}")
    print()

    for dataset in args.dataset:
        print(f"--- {dataset} ---")
        configs = generate_configs(dataset, config_dir)
        print(f"  Generated {len(configs)} config files in {config_dir}/")

        generate_shell_script(dataset, configs, script_dir)
        generate_summary_script(dataset, configs, script_dir)
        print()

    print("Next steps:")
    print("  1. Review configs in configs/grid_search/")
    print("  2. Run: bash scripts/run_grid_<dataset>.sh")
    print("  3. Analyze: python scripts/summarize_grid_<dataset>.py")


if __name__ == "__main__":
    main()
